# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  PSM_jaw:
    has_velocity_limits: true
    max_velocity: 0.40000000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  PSM_jaw_mimic_1:
    has_velocity_limits: true
    max_velocity: 0.40000000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  PSM_jaw_mimic_2:
    has_velocity_limits: true
    max_velocity: 0.40000000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  PSM_outer_roll:
    has_velocity_limits: true
    max_velocity: 0.40000000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  PSM_outer_wrist_pitch:
    has_velocity_limits: true
    max_velocity: 0.40000000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  PSM_outer_wrist_yaw:
    has_velocity_limits: true
    max_velocity: 0.40000000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  lbr_A1:
    has_velocity_limits: true
    max_velocity: 1.7104226669544429
    has_acceleration_limits: false
    max_acceleration: 0
  lbr_A2:
    has_velocity_limits: true
    max_velocity: 1.7104226669544429
    has_acceleration_limits: false
    max_acceleration: 0
  lbr_A3:
    has_velocity_limits: true
    max_velocity: 1.7453292519943295
    has_acceleration_limits: false
    max_acceleration: 0
  lbr_A4:
    has_velocity_limits: true
    max_velocity: 2.2689280275926285
    has_acceleration_limits: false
    max_acceleration: 0
  lbr_A5:
    has_velocity_limits: true
    max_velocity: 2.4434609527920612
    has_acceleration_limits: false
    max_acceleration: 0
  lbr_A6:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: false
    max_acceleration: 0
  lbr_A7:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: false
    max_acceleration: 0
  virtual_tip_dummy:
    has_velocity_limits: true
    max_velocity: 0.10000000000000001
    has_acceleration_limits: false
    max_acceleration: 0