# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - tooltip_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - lbr_A1
      - lbr_A2
      - lbr_A3
      - lbr_A4
      - lbr_A5
      - lbr_A6
      - lbr_A7
  tooltip_controller:
    type: FollowJointTrajectory
    joints:
      - PSM_outer_roll
      - PSM_outer_wrist_pitch
      - PSM_outer_wrist_yaw
      - PSM_jaw